bezkoder:
  app:
    jwtSecret : bezKoderSecretKey
    jwtExpirationMs : 86400000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  redis:
    host: 8.130.83.55
    password: 123456
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #数据库
      database: admin
      #验证库
      authentication-database: admin
      #用户（如果MongoDB没有配置授权验证的可以不用写验证信息）
      username: fbf
      #密码
#      password: 123456
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1245325661@qq.com  #发送邮件的邮箱地址
    password: tcflcazgcasuihia  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1245325661@qq.com  # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#系统的一些数据
AdminCode: "you are not Admin!"