server:
 port: 8081

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/db
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
bezkoder:
 app:
  jwtSecret : bezKoderSecretKey
  jwtExpirationMs : 86400000
